#!/bin/bash
if [[ $1 -eq 0 ]]; then
	qemu-system-i386 -drive if=none,file=/home/zuban32/Downloads/dsl1.iso,id=cdrom -drive if=none,index=2,file=/home/zuban32/Downloads/dsl.iso,id=fake -device ide-bridge,id=bridge,drive=fake -device scsi-cd,drive=cdrom,bus=bridge.0  2> ~/ide_bridge
else
	qemu-system-i386 -cdrom ~/Downloads/dsl.iso 2> ~/read_pio
fi
