#!/bin/bash
if [[ $1 -eq 0 ]]; then
	qemu-system-x86_64 \
	-drive if=none,file=/home/zuban32/Downloads/ubuntu.iso,id=cdrom,format=raw \
	-drive if=none,id=fake \
	-device ide-bridge,id=bridge,drive=fake \
	-device scsi-cd,drive=cdrom,bus=bridge.0 \
	-m 1024 \
	-enable-kvm
else
	qemu-system-x86_64 \
	-cdrom ~/Downloads/dsl.iso \
	-hda diskimage \
	-m 1024 \
	2> ~/read_pio
fi
